name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Secret scan (gitleaks)
        uses: zricethezav/gitleaks-action@v2
        with:
          args: "--no-banner -v"

      - name: Node env check
        uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i -g ts-node typescript

      - name: Python env check
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -c "print('python ok')"
